### ISSUE TITLE
Error whene start abixen-platform core

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [abixen/abixen-platform#1028]
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.1.RELEASE:start (default-cli) on project abixen-platform-core: Spring application did not start before the configured timeout (30000ms -> [Help 1
![capture](https://cloud.githubusercontent.com/assets/3809904/25083823/25dd6472-2351-11e7-8cda-f14b5f4307e9.JPG)]

**Comment by mariuszkumor** [comment]
@sidahmedbenkhaoua check this one please https://github.com/abixen/abixen-platform/issues/433
