### ISSUE TITLE
Create unit test for AclEntryBuilder.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#1251]
Do it similarly like for https://github.com/abixen/abixen-platform/blob/v-1-0-wave-2-refactor/abixen-platform-core/src/test/java/com/abixen/platform/core/domain/model/UserBuilderTest.groovy

**Comment by vinodpandey1** [comment]
@mariuszkumor starting on it today but it may take some time .
I forked it now and will start working on it .Will get back to you if i need any clarification regarding the implementation details

**Comment by vinodpandey1** [comment]
@mariuszkumor I dont see any class as AclEntryBuilder in code base .

**Comment by mariuszkumor** [comment]
@vinodpandey1 - https://github.com/abixen/abixen-platform/blob/v-1-0-wave-2-refactor/abixen-platform-core/src/main/java/com/abixen/platform/core/domain/model/AclEntryBuilder.java

**Comment by vinodpandey1** [comment]
@mariuszkumor can you share your skype id so that we can have a call directoly as i forked it from master but i dont have this directory there

**Comment by mariuszkumor** [comment]
@vinodpandey1 We work on https://github.com/abixen/abixen-platform/tree/v-1-0-wave-2-refactor

**Comment by vinodpandey1** [comment]
@mariuszkumor should i checkout the mentioned branch and create a pull request against the same

**Comment by mariuszkumor** [comment]
@vinodpandey1 Exactly :-)

**Comment by vinodpandey1** [comment]
@mariuszkumor  Got it switched to branch and got the Class under test or Class to be tested

**Comment by mariuszkumor** [comment]
@vinodpandey1 - remember please our naming convention. Your commit title should be:
Created unit test for AclEntryBuilder. Resolved #1251

**Comment by vinodpandey1** [comment]
@mariuszkumor okay so in the commit string there should be ticket number with # prepended right anywhere ?

**Comment by mariuszkumor** [comment]
@vinodpandey1 - yes, and past simple form of the task title. Overal - in your case, above is the correct commit title.

**Comment by vinodpandey1** [comment]
@mariuszkumor what is the branch naming convention ? should i create a separate branch or commit to my fork .

**Comment by mariuszkumor** [comment]
@vinodpandey1 - there is no naming convention for branches yet.

**Comment by mariuszkumor** [comment]
@vinodpandey1 - directly to yashodeepv:v-1-0-wave-2-refactor - but with --force. And let me know once done.

**Comment by vinodpandey1** [comment]
@mariuszkumor what is yashodeepv:v?

**Comment by vinodpandey1** [comment]
@mariuszkumor okay i am doing a commit and push and would be raising a pull request now .

**Comment by vinodpandey1** [comment]
@mariuszkumor not able to push

**Comment by vinodpandey1** [comment]
@mariuszkumor pushed the changes to my fork

**Comment by vinodpandey1** [comment]
@mariuszkumor raising a pull request

**Comment by vinodpandey1** [comment]
@mariuszkumor Please do let me know your feedback .
