### ISSUE TITLE
Tomcat-embed-jasper version is not working while running the localhost:8080

### ISSUE THREAD

**Issue by veenodp** [abixen/abixen-platform#1253]
Not able to up the web-client localhost:8080.
Exception:

java.lang.IllegalStateException: No Java compiler available
at org.apache.jasper.JspCompilationContext.createCompiler(JspCompilationContext.java:235)

**Comment by veenodp** [comment]
Solution: 
Need to add below dependency in pom.xml in web-client.

<dependency>
            <groupId>org.eclipse.jdt.core.compiler</groupId>
            <artifactId>ecj</artifactId>
            <version>4.6.1</version>
            <scope>provided</scope>
</dependency>

**Comment by mariuszkumor** [comment]
Thanks a lot @veenodp for this solution.
