### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by dhana250** [abixen/abixen-platform#1271]
I wasn't able to login to the application by using the credentials that has been mentioned in the documentation.

username joe.brown@abixen.com and password password - this is admin type of role
username leo.newman@abixen.com and password password - this is user type of role
username richard.smith@abixen.com and password password - this is editor type of role

**Comment by tanhui2333** [comment]
@dhana250 checkout out logs, make sure the db connection is ok.

**Comment by mariuszkumor** [comment]
@dhana250 Please attach a screenshot of eureka site.

**Comment by dhana250** [comment]
<img width="1438" alt="screen shot 2017-10-21 at 7 04 36 pm" src="https://user-images.githubusercontent.com/20112965/31856865-e6ca5300-b692-11e7-94b8-c327df29f52d.png">

**Comment by dhana250** [comment]
Now I was able to login into the application.
