### ISSUE TITLE
Can't run Gateway on my local

### ISSUE THREAD

**Issue by zoranf** [abixen/abixen-platform#1279]
I'm following the build tutorial in intelij and I get this error when I run gateway service:

[ERROR] Failed to execute goal on project abixen-platform-gateway: Could not resolve dependencies for project org.springframework.boot:abixen-platform-gateway:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.abixen:abixen-platform-common:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for com.abixen:abixen-platform-common:jar:1.0-SNAPSHOT: Could not transfer artifact com.abixen:abixen-platform-common:pom:1.0-SNAPSHOT from/to spring-releases (http://repo.spring.io/libs-release-local): Failed to transfer file: http://repo.spring.io/libs-release-local/com/abixen/abixen-platform-common/1.0-SNAPSHOT/abixen-platform-common-1.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]

**Comment by worldoframu** [comment]
Even i am facing the same issue. When clicked on this url: http://repo.spring.io/libs-release-local/com/abixen/abixen-platform-common/1.0-SNAPSHOT/abixen-platform-common-1.0-SNAPSHOT.pom
I am getting below rejection message.
{
  "errors" : [ {
    "status" : 409,
    "message" : "The repository 'libs-release-local' rejected the resolution of an artifact 'libs-release-local:com/abixen/abixen-platform-common/1.0-SNAPSHOT/abixen-platform-common-1.0-SNAPSHOT.pom' due to conflict in the snapshot release handling policy."
  } ]
}

@zoranf was this resolved for you?

**Comment by zoranf** [comment]
@worldoframu no

**Comment by mariuszkumor** [comment]
Looks like outdated, that's why I'm closing. If the issue still persists, please reopen and add more details.
