### ISSUE TITLE
Running on local windows machine, the web module is just blank

### ISSUE THREAD

**Issue by robarwebservices** [abixen/abixen-platform#1284]
I got abixen up and running and installed all included modules in the getting started guide. I could start all of the services successfully. 

However, when browsing to the admin web page, it just turns up blank. When opening up the chrome dev console, I see 404 errors for 90% of the resources, and a few 403 errors. 

Any thoughts on what might be the issue, or what to look into?

**Comment by syswuheng** [comment]
I encounter the same issue.
Who can help me?

**Comment by mariuszkumor** [comment]
Since I see no more comments here and the topic is really old I'm closing this issue. For me looks like some steps from WIKI have been skipped. If the problem still persists, please re-open.
