### ISSUE TITLE
Missing fonts for the datepicker component.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#168]
<img width="1417" alt="screen shot 2016-12-11 at 09 50 56" src="https://cloud.githubusercontent.com/assets/10467382/21079106/72f8fb96-bf87-11e6-80c6-61043908ccc9.png">

**Comment by alvin-reyes** [comment]
It's possible that the reason why it can't load those files is because the web server doesn't recognize the extensions.

**Comment by alvin-reyes** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/4479171/21492411/83db66d6-cbd2-11e6-99be-c91b8a4972f1.png)
