### ISSUE TITLE
Error during buiding the project.

### ISSUE THREAD

**Issue by aghabii** [abixen/abixen-platform#194]
I'm new with abixen-platform, i'm trying to build the project and i'm getting this error. any idea?
[ERROR] npm ERR! Windows_NT 6.3.9600
[ERROR] npm ERR! argv "D:\\workspaces\\abixen-platform\\abixen-platform-modules\\node\\node.exe" "D:\\workspaces\\abixen-platform\\abixen-platform-modules\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"
[ERROR] npm ERR! node v6.7.0
[ERROR] npm ERR! npm  v3.10.9
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! abixen-platform-modules@1.0.0 postinstall: `bower install`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the abixen-platform-modules@1.0.0 postinstall script 'bower install'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the abixen-platform-modules package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     bower install
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs abixen-platform-modules
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls abixen-platform-modules
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     D:\workspaces\abixen-platform\abixen-platform-modules\npm-debug.log

**Comment by mariuszkumor** [comment]
What maven version do you have ?

**Comment by mariuszkumor** [comment]
And did you try it with the newest version of Abixen Platform?

**Comment by aghabii** [comment]
Fixed, i got this error because intellij wasn't linked with github.exe.
What do you mean by newest version?i'm using this repo https://github.com/abixen/abixen-platform.git

**Comment by mariuszkumor** [comment]
I mean exactly this link, but the newest revision. It's OK. Good that works.
