### ISSUE TITLE
Add language switcher dropdown in AngularJS for the web client microservice

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#202]
Add an icon in selected place. Once icon is click, should open dropdown menu with positions:
[Flag] English
[Flag] Polish
[Flag] Russian
[Flag] Spanish
[Flag] Ukrainian

The dropdown should be similar to displayed after the avatar click, but contains flag icons and texts (language names).
Changing of language should trigger mockuped empty function in platformNavigation directive (add this function - function must pass new language as a parameter).
A template of this directive is placed in /common/navigation/html/platform-navigation.html

Will be needed to add a gulp rule in the web client microservice copying images to the static directory.

Icons you can take from here https://www.iconfinder.com/icons/92406/states_united_icon
Take size 48.

![screen shot 2016-12-18 at 12 11 02](https://cloud.githubusercontent.com/assets/10467382/21293213/ceb1d138-c51d-11e6-9672-e9198f903303.png)

**Comment by guramritpal-jft** [comment]
Work in progress.

**Comment by alvin-reyes** [comment]
This is done. Just need to test UI.

**Comment by alvin-reyes** [comment]
done. 
![image](https://cloud.githubusercontent.com/assets/4479171/21583678/e110943a-d059-11e6-930e-38bc102d447f.png)
