### ISSUE TITLE
loading front end page error

### ISSUE THREAD

**Issue by YogenRaii** [abixen/abixen-platform#205]
All microservices except hystrix-dashboard are running and gulp dev build is successful. But I'm getting this error while trying to load a page ( abixen-web-client microservices is running perfectly)
![web-client-error](https://cloud.githubusercontent.com/assets/14182415/21294887/226c673c-c516-11e6-84a8-8e020d8115f1.jpg)

**Comment by mariuszkumor** [comment]
Please paste screenshot from eureka site http://localhost:8761/

**Comment by YogenRaii** [comment]
![eureka](https://cloud.githubusercontent.com/assets/14182415/21294912/cef30042-c516-11e6-884e-ff4e8fa1ded6.jpg)

**Comment by mariuszkumor** [comment]
Can you open this url or 404 are you getting? http://localhost:9091/application/modules/abixen/lib/d3.min.js

**Comment by YogenRaii** [comment]
yes i can open,,,,and see the compiled js... i already tried these things,,, but couldn't come up with solution.

**Comment by mariuszkumor** [comment]
OK, and this http://localhost:9090/application/modules/abixen/lib/d3.min.js? If yes, check logs in gateway.

**Comment by YogenRaii** [comment]
I see... on gateway log, i can see that csrf token is being generated as:
2016-12-18 13:17:56 241 [DEBUG] [c=CsrfHeaderFilter] csrf token: 252f4691-218d-4237-b50c-5d09907202f8

And while trying to access js in 9090 port, i see message as below:
![web-client-error-js-access](https://cloud.githubusercontent.com/assets/14182415/21295510/979c8772-c524-11e6-9f4b-78067d06467b.jpg)

**Comment by mariuszkumor** [comment]
Did you do mvn install for the project? Or just run? And from what did you get url in the screenshot? It is not uses in the application.

**Comment by YogenRaii** [comment]
yes i did.... and when i try it again to make sure before my response... i got error with platform-modules which i opened new issue.... i want to keep this issue open unitil i get to web-client microserivce again

**Comment by YogenRaii** [comment]
Whenever i try to load page at localhost:8080/ .. i'm getting response as below:
`2016-12-18 16:22:31 079 [DEBUG] [c=ApplicationViewController] renderApplicationPage()
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 1
    relativeUrl: /application/modules/abixen/modules.min.js
    resourceLocation: BODY
    resourceType: JAVASCRIPT
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 1
    name: multi-visualization
    title: Multi Visualization
    description: This is a multi visualization module
    initUrl: /application/modules/abixen/multi-visualization/html/index.html
    serviceId: abixen-platform-modules
}
}
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 2
    relativeUrl: /application/modules/abixen/lib/d3.min.js
    resourceLocation: BODY
    resourceType: JAVASCRIPT
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 1
    name: multi-visualization
    title: Multi Visualization
    description: This is a multi visualization module
    initUrl: /application/modules/abixen/multi-visualization/html/index.html
    serviceId: abixen-platform-modules
}
}
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 3
    relativeUrl: /application/modules/abixen/lib/nv.d3.min.js
    resourceLocation: BODY
    resourceType: JAVASCRIPT
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 1
    name: multi-visualization
    title: Multi Visualization
    description: This is a multi visualization module
    initUrl: /application/modules/abixen/multi-visualization/html/index.html
    serviceId: abixen-platform-modules
}
}
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 4
    relativeUrl: /application/modules/abixen/lib/nv.d3.min.css
    resourceLocation: HEADER
    resourceType: CSS
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 1
    name: multi-visualization
    title: Multi Visualization
    description: This is a multi visualization module
    initUrl: /application/modules/abixen/multi-visualization/html/index.html
    serviceId: abixen-platform-modules
}
}
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 5
    relativeUrl: /application/modules/abixen/lib/angular-nvd3.min.js
    resourceLocation: BODY
    resourceType: JAVASCRIPT
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 1
    name: multi-visualization
    title: Multi Visualization
    description: This is a multi visualization module
    initUrl: /application/modules/abixen/multi-visualization/html/index.html
    serviceId: abixen-platform-modules
}
}
2016-12-18 16:22:31 131 [DEBUG] [c=ApplicationViewController] resource: com.abixen.platform.client.web.model.Resource
Object {
    id: 8
    relativeUrl: /application/modules/abixen/lib/roundProgress.min.js
    resourceLocation: BODY
    resourceType: JAVASCRIPT
    moduleType: com.abixen.platform.client.web.model.ModuleType
Object {
    id: 3
    name: kpi-chart
    title: KPI Chart
    description: This is a KPI chart module
    initUrl: /application/modules/abixen/kpi-chart/html/index.html
    serviceId: abixen-platform-modules
}
}
`

But, the rendering is failing because of js files load fail.

**Comment by mariuszkumor** [comment]
In log4j.properties set level 
log4j.rootLogger=DEBUG, CA

for web client, gateway and check logs after restart these microservices.
try execute:
http://localhost:9090/application/modules/abixen/lib/d3.min.js
http://localhost:8080/application/modules/abixen/lib/d3.min.js

**Comment by YogenRaii** [comment]
Did,,,, but some many logs for DEBUG level, so couldn't identify the problem :) .... am i the only one to get this error to date?

**Comment by alvin-reyes** [comment]
I had the same error earlier (just now). Did you run the services with -Dspring.profiles.active=dev VM argument?

**Comment by YogenRaii** [comment]
Yes i did, but it didn't solve for me :(

**Comment by alvin-reyes** [comment]
Can you try re-building the entire application but this time, use a clean command to delete the artifacts first.
 
`mvn clean install -DskipDocker`

**Comment by YogenRaii** [comment]
will try today and will let you know!

---------------------------------------------------------
Best Regards,

Yogen

Yogen Rai
Cell Phone: 641-980-8606
Email: Yogen.Rai.992@gmail.com

**Comment by mariuszkumor** [comment]
Yogen, this issue is similar to your one. Please check it out https://github.com/abixen/abixen-platform/issues/222

**Comment by YogenRaii** [comment]
@alvin-reyes i tried, but didn't work :(

**Comment by YogenRaii** [comment]
@mariuszkumor I'm following

**Comment by YogenRaii** [comment]
@mariuszkumor the problem is same, I tried with every way leaving no stone unturned. Need serious help :)

**Comment by mariuszkumor** [comment]
@YogenRaii Looks like you have a typo in configuration params of gateway micro service. I. e. 
-Dsprings.profiles.active=dev instead of 
-Dspring.profiles.active=dev

**Comment by YogenRaii** [comment]
you saved my life!!! literally i looked into it more than 20 times but didn't notice... thanks alot
