### ISSUE TITLE
Problem building the code using maven 

### ISSUE THREAD

**Issue by rbharath26** [abixen/abixen-platform#213]
Hi Team , 
I tried to run maven install - install -DskipDocker for C:/Users/bragh/IdeaProjects/abixen-platform/abixen-platform-modules and getting the below issue : Please let me know if any faced the issue ?

[ERROR] bower angular-svg-round-progressbar#0.3.8           ENOGIT git is not installed or not in the PATH
[ERROR] 
[WARNING] npm WARN abixen-platform-modules@1.0.0 No description
[issue scren.docx](https://github.com/abixen/abixen-platform/files/660407/issue.scren.docx)

[WARNING] npm WARN abixen-platform-modules@1.0.0 No repository field.
[WARNING] npm WARN abixen-platform-modules@1.0.0 No license field.
[ERROR] npm ERR! Windows_NT 10.0.14393
[ERROR] npm ERR! argv "C:\\Users\\bragh\\IdeaProjects\\abixen-platform\\abixen-platform-modules\\node\\node.exe" "C:\\Users\\bragh\\IdeaProjects\\abixen-platform\\abixen-platform-modules\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"

![Uploading image.png…]()

[ERROR] npm ERR! node v6.7.0
[ERROR] npm ERR! npm  v3.10.9
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! abixen-platform-modules@1.0.0 postinstall: `bower install`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the abixen-platform-modules@1.0.0 postinstall script 'bower install'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the abixen-platform-modules package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     bower install
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs abixen-platform-modules
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls abixen-platform-modules
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! Please include the following file with any support request:
[ERROR] npm ERR!     C:\Users\bragh\IdeaProjects\abixen-platform\abixen-platform-modules\npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----------------------------------

**Comment by mariuszkumor** [comment]
This message: 
[ERROR] bower angular-svg-round-progressbar#0.3.8 ENOGIT git is not installed or not in the PATH
means you don't have installed git on your machine, or you don't have added git to the path.

**Comment by rbharath26** [comment]
Thanks Mariusz...I did installed git .Looks like we need to restart IDE to recognize the same . 
Now the build is fixed .
