### ISSUE TITLE
abixen -webclient started -getting blank page hitting URL 

### ISSUE THREAD

**Issue by rbharath26** [abixen/abixen-platform#222]
Hi Team , 
I followed the steps in link 
https://github.com/abixen/abixen-platform/wiki/Getting-started-a-development 
Getting a blank page while hitting the URL :

http://localhost:8080/

Console looks good for Web client , But page not loading . I am using Firefox . I build the project  with 
[issue scren.docx](https://github.com/abixen/abixen-platform/files/662683/issue.scren.docx)
[issue scren.docx](https://github.com/abixen/abixen-platform/files/662685/issue.scren.docx)

DskipDocker  .

**Comment by alvin-reyes** [comment]
I got the same error earlier but I've manage to bring it up after restarting the services with the -Dspring.profiles.active=dev VM argument. Make sure to pass that when running the services except for eureka.

**Comment by rbharath26** [comment]
Hi Alvin ,
I will try it . By any chance in web client start up did you got this warnings:
"insufficient free space available after evicting expired cache entries "

INFO: Starting Servlet Engine: Apache Tomcat/8.5.5
_Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/gson-2.7.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache_
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/netty-common-4.0.27.Final.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/spring-boot-actuator-1.4.1.RELEASE.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/spring-cloud-commons-1.1.3.RELEASE.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/jackson-core-2.8.3.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/guice-grapher-4.0.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/commons-lang3-3.1.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/spring-cloud-context-1.1.3.RELEASE.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource
WARNING: Unable to add the resource at [/WEB-INF/lib/spring-oxm-4.3.3.RELEASE.jar] to the cache because there was insufficient free space available after evicting expired cache entries - consider increasing the maximum size of the cache
Dec 19, 2016 9:44:09 PM org.apache.catalina.webresources.Cache getResource

**Comment by alvin-reyes** [comment]
No I didn't get any warnings like that, but you can resolve this by clearing or increasing cache max size on your embedded tomcat.

**Comment by rbharath26** [comment]
Hi Alvin ,
I am trying to see the tomcat location ... Do you where I am using Intelli J  Community edition ..Its been hard to see where servers configured ? 

Thanks for the help !

**Comment by alvin-reyes** [comment]
The embedded tomcat is inside the JAR so you can only configure it via the Java code. Whenever you restart the server, the cache clears up so make sure that you terminate all processes when you re-run.

I'm using Eclipse IDE.

**Comment by mariuszkumor** [comment]
rbharath26, could you please attach JavaScrip console screen (of your plan page) ?

**Comment by rbharath26** [comment]
Hi Mariusz , 
The issue seems to be resolved now . I am able to login ..Thanks Alvin /Mariusz .Hopefully -Dspring.profiles.active=dev fixed it .

**Comment by YogenRaii** [comment]
@rbharath26 you set Dspring.profiles.active=dev in abixen-platform (root) too? I set this property on every microservices except eureka, but i'm still getting this error :(

**Comment by YogenRaii** [comment]
Guys, help me out. Please look into [#205 ](https://github.com/abixen/abixen-platform/issues/205#issuecomment-268271108)for the issue.
