### ISSUE TITLE
Migrate logger to log4j 2 for the core microservice

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#228]
Base on https://github.com/abixen/abixen-platform/commit/c7c95a2f10b7ab2d69f3483571c9338eff3ca0d7

Do it similarly. Compile all source (mvn install -DskipDocker) once change in order to check if install is successful.

**Comment by alvin-reyes** [comment]
I can't seem to push my local branch to our repo. Can you make sure that I have the correct permissions?

**Comment by mariuszkumor** [comment]
Because you must push to your repo, but i see you did already :-)

2016-12-21 5:20 GMT+01:00 Alvin Reyes <notifications@github.com>:

**Comment by alvin-reyes** [comment]
A new pull request is already on the queue for this. Please review and accept.
