### ISSUE TITLE
Change an input on a popup in the Magic Number configuration panel of the Icon Class field.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#24]
Needed selection of icons from the fontawesome.

http://fontawesome.io/icons/

<img width="1183" alt="screen shot 2016-11-05 at 21 54 49" src="https://cloud.githubusercontent.com/assets/10467382/20033563/750fd6de-a3a3-11e6-8a4a-97b08151eb25.png">

When user click the input, a modal window should open as in the below picture:

![screen shot 2016-12-21 at 15 03 34](https://cloud.githubusercontent.com/assets/10467382/21399863/c1bf7a6a-c7ad-11e6-874b-f9fe92182fe1.png)

Content of the modal should have all icons from the fontawesome. Icon must be selectable as the screen presented. Must be added vertical scrollbar, because there will be a lot of icons. In the input should be put icon class name: i. e. fa fa-bar-chart
Buttons save and cancel make similarly as in other places in the application.

Please create an AngularJS component of the modal window in web client microservice and apply for the above input. Modal window will be using for another one functionality in the application, that's why must be generic and located in common.

<img width="736" alt="screen shot 2016-12-21 at 18 49 33" src="https://cloud.githubusercontent.com/assets/10467382/21399998/494a6058-c7ae-11e6-8fcd-2cb844461e54.png">

**Comment by alvin-reyes** [comment]
Selection modal works now but some font-awesome images are not showing. Discovered that not all font-awesome are installed in the app. Need to find a way to get them to display.

**Comment by mariuszkumor** [comment]
@alvin-reyes How many icons are displaying for now? Installation of additional icons should be realised  as a next task.

**Comment by alvin-reyes** [comment]
![image](https://cloud.githubusercontent.com/assets/4479171/21477128/f0869d58-cb0c-11e6-9202-a4bb1542b22a.png)
