### ISSUE TITLE
Add values of fields length to interfaces of the core microservice

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#246]
For now there is one large file com.abixen.platform.core.util.ModelKeys keeping values of field lengths. We need to move these values to particular interfaces of domain and use in domain classes as import from interface.

I. e. field public static final int USERNAME_MIN_LENGTH = 3; move to com.abixen.platform.core.model.UserBase and use it in:
com.abixen.platform.core.model.impl.User
com.abixen.platform.core.form.UserForm

At the end remove the com.abixen.platform.core.util.ModelKeys file.

**Comment by nagukothapalli** [comment]
Please correct me if am wrong .

Need to create a com.abixen.platform.core.model.UserBase  as interface and add uses  related entries present in  Model keys .
 and Use it in
com.abixen.platform.core.model.impl.User
com.abixen.platform.core.form.UserForm

Delete those entries in Model keys

Uses Entries :  

    public static final int USERNAME_MIN_LENGTH = 3;
    public static final int USERNAME_MAX_LENGTH = 32;

**Comment by nagukothapalli** [comment]
and one more thing this story is  only for User Entries  or we need to migrate  all the entries from modelkkeys ?

**Comment by mariuszkumor** [comment]
hi,
com.abixen.platform.core.model.UserBase already exists. Just check in
com.abixen.platform.core.model.impl.User - this class implements it.
com.abixen.platform.core.model.impl.User is located in common

Rest is OK :-)

2016-12-22 15:42 GMT+01:00 Nagu Kothapalli <notifications@github.com>:

**Comment by mariuszkumor** [comment]
All entries across core microservice :-)

2016-12-22 15:44 GMT+01:00 Nagu Kothapalli <notifications@github.com>:

**Comment by nagukothapalli** [comment]
if am not wrong All this entries  in  Model keys, we  need to  move to userbase  interface ?

```
  //FIXME - what is name?
    public static final int NAME_MAX_LENGTH = 300;


    public static final int USERNAME_MIN_LENGTH = 3;
    public static final int USERNAME_MAX_LENGTH = 32;

    public static final int SCREEN_NAME_MIN_LENGTH = 3;
    public static final int SCREEN_NAME_MAX_LENGTH = 32;

    public static final int PASSWORD_MAX_LENGTH = 60;

    public static final int FIRST_NAME_MIN_LENGTH = 2;
    public static final int FIRST_NAME_MAX_LENGTH = 64;

    public static final int MIDDLE_NAME_MIN_LENGTH = 2;
    public static final int MIDDLE_NAME_MAX_LENGTH = 64;

    public static final int LAST_NAME_MIN_LENGTH = 2;
    public static final int LAST_NAME_MAX_LENGTH = 64;

    public static final int ROLE_NAME_MIN_LENGTH = 5;
    public static final int ROLE_NAME_MAX_LENGTH = 20;

    public static final int LAYOUT_TITLE_MIN_LENGTH = 6; //?
    public static final int LAYOUT_TITLE_MAX_LENGTH = 40;

    public static final int LAYOUT_CONTENT_MIN_LENGTH = 10;
    public static final int LAYOUT_CONTENT_MAX_LENGTH = 4000; //?

    public static final int LAYOUT_ICON_FILE_NAME_MAX_LENGTH = 100;

    public static final int MODULE_TITLE_MIN_LENGTH = 6;
    public static final int MODULE_TITLE_MAX_LENGTH = 40;

    public static final int MODULE_DESCRIPTION_MAX_LENGTH = 100;

    public static final int MODULETYPE_NAME_MIN_LENGTH = 5;
    public static final int MODULETYPE_NAME_MAX_LENGTH = 20;

    public static final int MODULETYPE_TITLE_MIN_LENGTH = 6;
    public static final int MODULETYPE_TITLE_MAX_LENGTH = 40;

    public static final int MODULETYPE_DESCRIPTION_MIN_LENGTH = 40;
    public static final int MODULETYPE_DESCRIPTION_MAX_LENGTH = 40;

    public static final int PAGE_NAME_MIN_LENGTH = 5;
    public static final int PAGE_NAME_MAX_LENGTH = 20;

    public static final int PAGE_TITLE_MIN_LENGTH = 6;
    public static final int PAGE_TITLE_MAX_LENGTH = 40;

    public static final int PAGE_DESCRIPTION_MIN_LENGTH = 40;
    public static final int PAGE_DESCRIPTION_MAX_LENGTH = 40;

    public static final int RESOURCE_RELATIVE_URL_MIN_LENGTH = 3;
    public static final int RESOURCE_RELATIVE_URL_MAX_LENGTH = 250;

    public static final int RESOURCE_SERVICE_ID_MIN_LENGTH = 1;
    public static final int RESOURCE_SERVICE_ID_MAX_LENGTH = 255;

    public static final int HASH_KEY_MAX_LENGTH = 60;

    /**
     * IPv4-mapped IPv6 (45 bytes)
     */
    public static final int REGISTRATION_IP_MAX_LENGTH = 45;

    public static final char COMMA = ',';
    public static final char TAB = '\t';

    public static final int ACL_CLASS_NAME_MAX_LENGTH = 250;
```

**Comment by nagukothapalli** [comment]
For me all the entries present in Model Keys seems to related to user  only :)

**Comment by mariuszkumor** [comment]
No, not to user base interface. To interfaces relevant to particular
domains.

i. e. a few to user, some to module, some to role, and so on

2016-12-22 15:53 GMT+01:00 Nagu Kothapalli <notifications@github.com>:

**Comment by mariuszkumor** [comment]
No, i. e.. ModelKeys.PAGE_DESCRIPTION_MAX_LENGTH is used in page domain.

pls check all domains.

2016-12-22 15:56 GMT+01:00 Nagu Kothapalli <notifications@github.com>:

**Comment by nagukothapalli** [comment]
Ok . Got it

**Comment by nagukothapalli** [comment]
Hi @mariuszkumor 

There were few keys USERNAME_MAX_LENGTH, FIRST_NAME_MAX_LENGTH, LAST_NAME_MAX_LENGTH Used in both **User and UserForm**    classes . 
both classes are not implementing the same interface.
So we need to put thease  entries in two diffrent  interfaces **(Form,UserBase)** .
 this will causes duplicate entries in both the interfaces.

is this fine with you . Please confirm

**Comment by mariuszkumor** [comment]
No, in Forms you have to refer to UserBase interface i.e UserBase. USERNAME_MAX_LENGTH

btw: check other forms, the can have references to WebKeys class as well.

**Comment by nagukothapalli** [comment]
Hey @mariuszkumor 

Raised a pull request. Please review.
