### ISSUE TITLE
Create model of comments feature.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#256]

**Comment by mariuszkumor** [comment]
Create a domain Comment in the core microservice with all necessary interfaces, similarly as other domains i.e. Page. Extend by AuditingModel.

Add field:

String message
Comment parent

Create liquidate schema for it with sequence.
Remember about H2 file dropping once changes in liquibase are done https://github.com/abixen/abixen-platform/issues/207

**Comment by nagukothapalli** [comment]
hey @mariuszkumor 

Do I need to add respative comment  changelog xml and comment-data.csv files as in liquebase prperties
if Yes wt are the feilds in comment entity

As of Now i have Added com.abixen.platform.core.model.impl.Comment  extends AuditingModel class and Respative CommentBase class in common modules.   :)
and one more thing like Page  do i need to create CommentWeb class also

**Comment by mariuszkumor** [comment]
@nagukothapalli 

yes, you need add only comment changelog xml , The comment-data.csv is unneeded for now :-) Also in sequences-changelog.xml must add comment sequence.
CommentWeb is needed as well.

**Comment by nagukothapalli** [comment]
Do have any specific schema for comment entity ?

**Comment by mariuszkumor** [comment]
No, please make similarly like i.e. Page

24 gru 2016 10:15 "Nagu Kothapalli" <notifications@github.com> napisał(a):

Do have any specific schema for comment entity ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/abixen/abixen-platform/issues/256#issuecomment-269076480>,
or mute the thread
