### ISSUE TITLE
Create a service and a save method of comments feature.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#258]
Create a CommentForm object with fields:
String message
CommentWeb parentComment

Pass an object CommentForm commentForm to the save method in CommentService.
For service make an implementation CommentServiceImpl.

A creation of this functionality requires a creation of CommentRepository.

At the end, make an unit test covering a see method of CommentService.

**Comment by nagukothapalli** [comment]
i think , we need to  add CommentBuilderImpl and CommentBuilder also in respective packages like others
i.e Page and Role

**Comment by mariuszkumor** [comment]
@nagukothapalli, OK - you can add it. I didn't write it, because the comment is pretty simple domain. But ok - let's add it!

**Comment by nagukothapalli** [comment]
@mariuszkumor 

**Answer when ever you free.  Not to be urgent**

is below methods are sufficient in comment service? . if not Please suggest if any

```
public interface CommentService {

    void save(CommentForm commentForm);
    Comment buildComment(CommentForm commentForm);

   }

```

**Comment by mariuszkumor** [comment]
Yes,  they are.

26 gru 2016 19:41 "Nagu Kothapalli" <notifications@github.com> napisał(a):

**Comment by nagukothapalli** [comment]
@mariuszkumor 

below are the comment service methods,please let me know if any changes

```

public interface CommentService {

    Comment buildComment(CommentForm commentForm);

    Comment saveComment(Comment Comment);

    CommentForm saveComment(CommentForm CommentForm);

    Comment updateComment(Comment Comment);

    CommentForm updateComment(CommentForm CommentForm);

    void deleteComment(Long id);

    Page<Comment> findAllPages(Pageable pageable);

    List<Comment> findAllComments();

    Comment findComment(Long id);

}

```

**Comment by mariuszkumor** [comment]
Looks like misunderstanding. This interface is enough:

public interface CommentService {

    void save(CommentForm commentForm);
    Comment buildComment(CommentForm commentForm);

   }

**Comment by nagukothapalli** [comment]
Ok , Thanks for confirmning

**Comment by nagukothapalli** [comment]
@mariuszkumor 

Raised a pull request for comment service, please review let me know if any changes
