### ISSUE TITLE
error when mvn install -DskipDocker 

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [abixen/abixen-platform#26]
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:
install-node-and-npm (install node and npm) on project abixen-platform-modules:
Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin
:0.0.22:install-node-and-npm failed: A required class was missing while executin
g com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm: org/slf
4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:0.0.22
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/works/maven/repository/com/github/eirslett/frontend-m
aven-plugin/0.0.22/frontend-maven-plugin-0.0.22.jar
[ERROR] urls[1] = file:/D:/works/maven/repository/com/github/eirslett/frontend-p
lugin-core/0.0.22/frontend-plugin-core-0.0.22.jar
[ERROR] urls[2] = file:/D:/works/maven/repository/org/codehaus/jackson/jackson-m
apper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/D:/works/maven/repository/org/codehaus/jackson/jackson-c
ore-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/D:/works/maven/repository/org/apache/commons/commons-com
press/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/D:/works/maven/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/D:/works/maven/repository/commons-io/commons-io/1.3.2/co
mmons-io-1.3.2.jar
[ERROR] urls[7] = file:/D:/works/maven/repository/org/apache/httpcomponents/http
client/4.3.1/httpclient-4.3.1.jar
[ERROR] urls[8] = file:/D:/works/maven/repository/org/apache/httpcomponents/http
core/4.3/httpcore-4.3.jar
[ERROR] urls[9] = file:/D:/works/maven/repository/commons-logging/commons-loggin
g/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[10] = file:/D:/works/maven/repository/commons-codec/commons-codec/1
.6/commons-codec-1.6.jar
[ERROR] urls[11] = file:/D:/works/maven/repository/javax/enterprise/cdi-api/1.0/
cdi-api-1.0.jar
[ERROR] urls[12] = file:/D:/works/maven/repository/javax/annotation/jsr250-api/1
.0/jsr250-api-1.0.jar
[ERROR] urls[13] = file:/D:/works/maven/repository/com/google/guava/guava/10.0.1
/guava-10.0.1.jar
[ERROR] urls[14] = file:/D:/works/maven/repository/com/google/code/findbugs/jsr3
05/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[15] = file:/D:/works/maven/repository/org/sonatype/sisu/sisu-guice/
3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[16] = file:/D:/works/maven/repository/aopalliance/aopalliance/1.0/a
opalliance-1.0.jar
[ERROR] urls[17] = file:/D:/works/maven/repository/org/eclipse/sisu/org.eclipse.
sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[18] = file:/D:/works/maven/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[19] = file:/D:/works/maven/repository/org/codehaus/plexus/plexus-co
mponent-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[20] = file:/D:/works/maven/repository/org/apache/maven/plugin-tools
/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[21] = file:/D:/works/maven/repository/com/googlecode/slf4j-maven-pl
ugin-log/slf4j-maven-plugin-log/1.0.0/slf4j-maven-plugin-log-1.0.0.jar
[ERROR] urls[22] = file:/D:/works/maven/repository/org/sonatype/plexus/plexus-bu
ild-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[23] = file:/D:/works/maven/repository/org/codehaus/plexus/plexus-ut
ils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR]
[ERROR] -----------------------------------------------------: org.slf4j.helpers
.MarkerIgnoringBase
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContaine
rException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :abixen-platform-modules

**Comment by mariuszkumor** [comment]
Try to upgrade com.github.eirslett:frontend-maven-plugin to version 0.0.23 is released, that should fix this problem. Version 0.0.22 doesn't work with Maven 3.3.1

**Comment by sidahmedbenkhaoua** [comment]
thnak's for replay work fine
