### ISSUE TITLE
A JavaScript error once the configuration of the MagicNumber is open.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#280]
https://docs.angularjs.org/error/$injector/unpr?p0=faModalSelectionWindowProvider%20%3C-NaNaModalSelectionWindow%20%3C-%20MagicNumberModuleConfigurationController

<img width="1440" alt="screen shot 2016-12-26 at 11 57 41" src="https://cloud.githubusercontent.com/assets/10467382/21480942/aa1e233a-cb62-11e6-973a-5ead8450b935.png">

**Comment by alvin-reyes** [comment]
Yes. I missed checking in the application.js file.
