### ISSUE TITLE
Create a module Theme in the admin panel

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#292]
Add a list view for themes similarly as for the user module user-list.controller.js
Create needed JavaScript files of AngularJS modules and html files.

**Comment by alvin-reyes** [comment]
This is done on my local branch. Tested the module by:

1) Added the link the navigation
2) Return the list of pre-defined themes

Since the only task is to create the js and html files, I'll remove the navigation entry for themes on this commit.

**Comment by alvin-reyes** [comment]
![image](https://cloud.githubusercontent.com/assets/4479171/21560163/8e66a824-ce28-11e6-831c-c87c13d0d789.png)

**Comment by alvin-reyes** [comment]
![image](https://cloud.githubusercontent.com/assets/4479171/21566842/e5db0c3e-ce74-11e6-8f55-27d7df1aa65e.png)
