### ISSUE TITLE
Create frontend layer of themes uploader

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#322]
Make it similarly as in layout's icon uploader in the admin panel, or user's avatar. Accept only *.zip files.

**Comment by alvin-reyes** [comment]
Done. Just need to test it further.

![image](https://cloud.githubusercontent.com/assets/4479171/21598746/f5046b70-d12f-11e6-81fe-63926f6c3d65.png)

**Comment by alvin-reyes** [comment]
Do we need to add a title field? or our theme module will generate the theme with the title already in it?

**Comment by mariuszkumor** [comment]
@alvin-reyes I think, the title will be placed in some deployment descriptor inside of a theme package.
