### ISSUE TITLE
Create a backend layer of themes uploader

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#323]
Upload *.zip files unzip to the themes directory. Add suffix (1), (2), (3)... (n) if name already exists in the  themes directory.

**Comment by alvin-reyes** [comment]
Can we use datetime stamp, instead of an increment? 
foldername_MMDDYYYHHMI

**Comment by mariuszkumor** [comment]
@alvin-reyes for now you can omit the suffix feature. Just assume the name every time is other.

**Comment by alvin-reyes** [comment]
This is done. Just need to do a few more test.
