### ISSUE TITLE
Migrate fields of the page edit form in the admin panel 

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#447]
In the admin/modules/page/edit.html set title and description fields similarly as in application/modules/page/html/add.html

Also create a file page.translate.config.js similarly to user.translate.config.js and add translations for English.

Migrate page-detail.controller.js to style similarly user-details.controller.js

**Comment by rajanpupa** [comment]
1. Hi mariuszkumor, how do i reach to the admin/modules/page/edit.html from ui?, how do i reach to application/modules/page/html/add.html?
