### ISSUE TITLE
Zipkin run from docker-compose fails and exits during first start 

### ISSUE THREAD

**Issue by cloudowski** [abixen/abixen-platform#600]
Probably because it reaches some kind of timeout when it tries to reach configuration service. It needs to be restarted manually and then it runs perfectly.

**Comment by mariuszkumor** [comment]
Here you may set bigger value of max attempts. Try it out if helps.

<img width="1440" alt="screen shot 2017-02-05 at 13 58 43" src="https://cloud.githubusercontent.com/assets/10467382/22626332/469ff6f8-ebab-11e6-84b9-58f757a058f1.png">

**Comment by mariuszkumor** [comment]
@cloudowski shall we close this issue ?
