### ISSUE TITLE
Add prefixes to applications http endpoints for docker profile

### ISSUE THREAD

**Issue by cloudowski** [abixen/abixen-platform#650]
It will simplify and unify configuration of load balancer for docker (traefik) and aws (Application Load Balancer).
Prefixes are needed only for applications that need load balancing.

**Comment by cloudowski** [comment]
@mariuszkumor I will need a help with this :-) It blocks me from testing aws configuration.

**Comment by cloudowski** [comment]
@mariuszkumor - do users need to be able to reach other endpoints besides web-client? Cause if not we can leave load balancer only for this component and the rest will be used internally and directly with endpoints fetched from eureka.

**Comment by mariuszkumor** [comment]
@cloudowski - the users need to be able to reach only web-client endpoints. The web client micro service is all what the users sees. For internally connections would be good to use client side loadbalancers.

**Comment by cloudowski** [comment]
Ok, let's close it then.
