### ISSUE TITLE
Prepare MySQL database connection for sample data.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#663]
In Business Intelligence Service there is database-connection-postgres.csv file for PostgreSQL database connection. In import.xml there is import realised
<property name="databaseConnectionFile" value="database-connection-postgres" dbms="postgresql"/>

Do it similarly for MySQL. Check if charts from http://localhost:8080/#/3 are loading (Attache screenshot in comments of this task).

**Comment by rajanpupa** [comment]
<img width="795" alt="abixen663" src="https://cloud.githubusercontent.com/assets/1931698/23288346/1843b762-fa11-11e6-9133-9e347d97f213.PNG">
 
Image generated by changing the datasource to mysql.

**Comment by rajanpupa** [comment]
[abixen_platform_businessintelligence_service.zip](https://github.com/abixen/abixen-platform/files/798265/abixen_platform_businessintelligence_service.zip)
