### ISSUE TITLE
Prepare Oracle database connection for sample data.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#664]
In Business Intelligence Service there is database-connection-postgres.csv file for PostgreSQL database connection. In import.xml there is import realised
<property name="databaseConnectionFile" value="database-connection-postgres" dbms="postgresql"/>

Do it similarly for Oracle. Check if charts from http://localhost:8080/#/3 are loading (Attache screenshot in comments of this task).

**Comment by rajanpupa** [comment]
[oracle.sql.zip](https://github.com/abixen/abixen-platform/files/819092/oracle.sql.zip)

**Comment by YogenRaii** [comment]
I tried with 
`<property name="databaseConnectionFile" value="database-connection-oracle" dbms="h2"/>`
 with 
`<property name="databaseConnectionFile" value="database-connection-h2" dbms="h2"/>`
commented
and 
put back

`<property name="databaseConnectionFile" value="database-connection-oracle" dbms="oracle"/>`

:)
