### ISSUE TITLE
Create a method to validation if structure contains all template's variables in service StructureServiceImpl.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#701]
Here is a definition of structure https://github.com/abixen/abixen-platform/issues/700

**Comment by rbharath26** [comment]
Sample format of an xml structure:

<?xml version="1.0" encoding="UTF-8"?>
<fields>
   <field name="someName1" type="text"/>
   <field name="someName2" type="textArea"/>
   <field name="someName3" type="richTextArea"/>
   <field name="someName4" type="date"/>
</fields>

Sample format of a html template:

Hello ${someName1}! 
This is something else: ${someName2}
And this is rich editor's text: ${someName3}
Born date: ${someName4}
