### ISSUE TITLE
Comment's input appears outside of module container.

### ISSUE THREAD

**Issue by mariuszkumor** [abixen/abixen-platform#744]
<img width="1131" alt="screen shot 2017-02-27 at 20 53 03" src="https://cloud.githubusercontent.com/assets/10467382/23377084/de14f594-fd2e-11e6-8a27-5fc48a5840e7.png">

<img width="1440" alt="screen shot 2017-02-27 at 21 04 09" src="https://cloud.githubusercontent.com/assets/10467382/23377448/5fb0a412-fd30-11e6-8df2-8accc66890d8.png">

**Comment by shaposhi** [comment]
![comment_add_form_inside](https://cloud.githubusercontent.com/assets/24605749/23377927/f0fe7646-fd31-11e6-8b89-f03178e066e9.JPG)

form inside main comments div

**Comment by mariuszkumor** [comment]
Yes, it is. But displays outside of the directive area. Looks like CSS  issue.
