### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by pmaingi** [abixen/abixen-platform#830]
Is there a way i can create rest api with abixen platform. Maybe provide an example as am thinking of using it to create a rest api i.e using @RestController to ensures that you will return a Java Object plus convert the response to JSON/XML automatically.

Thanks

**Comment by mariuszkumor** [comment]
@pmaingi of course there is an opportunity to create the Rest API. However I'd like to ask you, what kind of case are you thinking of?

**Comment by pmaingi** [comment]
Am thinking of creating a money remittance api based on abixen platform whereby i will need to expose rest endpoints. See an example www.worldremit.com.

**Comment by mariuszkumor** [comment]
@pmaingi it's hard to say, what is in the backend of your example. If you need expose the Rest API endpoints, please find here https://github.com/abixen/abixen-platform/blob/master/abixen-platform-business-intelligence-service/src/main/java/com/abixen/platform/service/businessintelligence/multivisualisation/controller/ChartModuleConfigurationController.java an example how we do it in Abixen Platform. There are much more examples in the source code. The documentation we are going to within 1 month.

**Comment by pmaingi** [comment]
@mariuszkumor Let me look on the example you provided. In my case i will have different clients i.e android, ios and web. 
Documentation would be really helpful.

Thank you.
